apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: catalogue
  template:
    metadata:
      labels:
        tier: catalogue
    spec:
      containers:
        - name: cart
          image: 863518461004.dkr.ecr.us-east-1.amazonaws.com/catalogue:latest
